version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - pip install -U numpydoc

sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
  system_packages: true
